def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
    'UNSTABLE': 'warning'
]
pipeline {
    agent any
    tools {
        maven "MAVEN3.9"
        jdk "JDK17"
    }
    
    environment {
        cluster="vproappprod"
        service="vprofileapptask-service-z54sqkql"
    }

    stages {

        stage('Deploy to Production') {
            steps {
                withAWS(region: 'us-west-2', credentials: 'awscreds') {
                    sh """
                        aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment
                    """
                }
            }
        }
    }
        
        

        
        
    post {
        always {
            echo "slack notification"
            slackSend (channel: '#jenkinscicd', color: COLOR_MAP[currentBuild.currentResult], message: "Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            cleanWs()
        }
    }
}